// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fixB
void fixB(arma::mat& B, Rcpp::Nullable<Rcpp::NumericMatrix> R_);
RcppExport SEXP _bifacLpRot_fixB(SEXP BSEXP, SEXP R_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type R_(R_SEXP);
    fixB(B, R_);
    return R_NilValue;
END_RCPP
}
// freeR
arma::vec freeR(arma::mat& R);
RcppExport SEXP _bifacLpRot_freeR(SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(freeR(R));
    return rcpp_result_gen;
END_RCPP
}
// commutation_matrix
arma::mat commutation_matrix(int p, int q);
RcppExport SEXP _bifacLpRot_commutation_matrix(SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(commutation_matrix(p, q));
    return rcpp_result_gen;
END_RCPP
}
// ALM_cpp
Rcpp::List ALM_cpp(arma::mat& A, Rcpp::Nullable<arma::mat> Phi0_, Rcpp::Nullable<arma::mat> Bstart_, Rcpp::Nullable<arma::mat> Phi_, double rho, double t, int maxit_ou, int maxit_in, int hesit, bool orthogonal, double tol1, double tol2, double tol3, bool verbose, int v_every, double Lmax, double c1, double c2, double p);
RcppExport SEXP _bifacLpRot_ALM_cpp(SEXP ASEXP, SEXP Phi0_SEXP, SEXP Bstart_SEXP, SEXP Phi_SEXP, SEXP rhoSEXP, SEXP tSEXP, SEXP maxit_ouSEXP, SEXP maxit_inSEXP, SEXP hesitSEXP, SEXP orthogonalSEXP, SEXP tol1SEXP, SEXP tol2SEXP, SEXP tol3SEXP, SEXP verboseSEXP, SEXP v_everySEXP, SEXP LmaxSEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Phi0_(Phi0_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Bstart_(Bstart_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Phi_(Phi_SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_ou(maxit_ouSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_in(maxit_inSEXP);
    Rcpp::traits::input_parameter< int >::type hesit(hesitSEXP);
    Rcpp::traits::input_parameter< bool >::type orthogonal(orthogonalSEXP);
    Rcpp::traits::input_parameter< double >::type tol1(tol1SEXP);
    Rcpp::traits::input_parameter< double >::type tol2(tol2SEXP);
    Rcpp::traits::input_parameter< double >::type tol3(tol3SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type v_every(v_everySEXP);
    Rcpp::traits::input_parameter< double >::type Lmax(LmaxSEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(ALM_cpp(A, Phi0_, Bstart_, Phi_, rho, t, maxit_ou, maxit_in, hesit, orthogonal, tol1, tol2, tol3, verbose, v_every, Lmax, c1, c2, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bifacLpRot_fixB", (DL_FUNC) &_bifacLpRot_fixB, 2},
    {"_bifacLpRot_freeR", (DL_FUNC) &_bifacLpRot_freeR, 1},
    {"_bifacLpRot_commutation_matrix", (DL_FUNC) &_bifacLpRot_commutation_matrix, 2},
    {"_bifacLpRot_ALM_cpp", (DL_FUNC) &_bifacLpRot_ALM_cpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_bifacLpRot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
