// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fixB
void fixB(arma::mat& B, Rcpp::Nullable<Rcpp::NumericMatrix> R);
RcppExport SEXP _bifacLpRot_fixB(SEXP BSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type R(RSEXP);
    fixB(B, R);
    return R_NilValue;
END_RCPP
}
// freeR
arma::vec freeR(arma::mat& R);
RcppExport SEXP _bifacLpRot_freeR(SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(freeR(R));
    return rcpp_result_gen;
END_RCPP
}
// ALM_cpp
Rcpp::List ALM_cpp(Rcpp::Nullable<arma::mat> A0_, Rcpp::Nullable<arma::mat> Phi0_, Rcpp::Nullable<arma::mat> Bstart_, Rcpp::Nullable<arma::mat> Phistart_, double rho, double t, int maxit_ou, int maxit_in, int maxit_bt, bool orthogonal, double tol1, double tol2, double tol3, bool verbose, int v_every, double c1, double c2, double p, const double rho_max, const double delta);
RcppExport SEXP _bifacLpRot_ALM_cpp(SEXP A0_SEXP, SEXP Phi0_SEXP, SEXP Bstart_SEXP, SEXP Phistart_SEXP, SEXP rhoSEXP, SEXP tSEXP, SEXP maxit_ouSEXP, SEXP maxit_inSEXP, SEXP maxit_btSEXP, SEXP orthogonalSEXP, SEXP tol1SEXP, SEXP tol2SEXP, SEXP tol3SEXP, SEXP verboseSEXP, SEXP v_everySEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP pSEXP, SEXP rho_maxSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type A0_(A0_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Phi0_(Phi0_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Bstart_(Bstart_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Phistart_(Phistart_SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_ou(maxit_ouSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_in(maxit_inSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_bt(maxit_btSEXP);
    Rcpp::traits::input_parameter< bool >::type orthogonal(orthogonalSEXP);
    Rcpp::traits::input_parameter< double >::type tol1(tol1SEXP);
    Rcpp::traits::input_parameter< double >::type tol2(tol2SEXP);
    Rcpp::traits::input_parameter< double >::type tol3(tol3SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type v_every(v_everySEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_max(rho_maxSEXP);
    Rcpp::traits::input_parameter< const double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(ALM_cpp(A0_, Phi0_, Bstart_, Phistart_, rho, t, maxit_ou, maxit_in, maxit_bt, orthogonal, tol1, tol2, tol3, verbose, v_every, c1, c2, p, rho_max, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bifacLpRot_fixB", (DL_FUNC) &_bifacLpRot_fixB, 2},
    {"_bifacLpRot_freeR", (DL_FUNC) &_bifacLpRot_freeR, 1},
    {"_bifacLpRot_ALM_cpp", (DL_FUNC) &_bifacLpRot_ALM_cpp, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_bifacLpRot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
